language: node_js

node_js:

  - '6.10.0'
  - '4.2.6'
  - '5.2.0'

cache:
  directories:
    - node_modules
before_install:
    - npm install

script:
 － npm run test
after_script:
  - npm run coveralls
